# Generated by Django 4.2.7 on 2026-03-28 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_shopkeeperproduct_vendorproduct_and_more'),
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.shopkeeperproduct'),
        ),
    ]
