# Generated by Django 4.2.7 on 2026-03-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('SHOPKEEPER', 'Shopkeeper'), ('DELIVERY', 'Delivery Partner')], default='CUSTOMER', max_length=20),
        ),
    ]
