# Generated by Django 5.2.8 on 2026-03-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_approved_approvalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
    ]
