# Generated by Django 5.2.8 on 2026-03-30 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_ai_verification_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents/'),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_decision',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('REAL', 'Real'), ('SUSPICIOUS', 'Suspicious')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
