# Generated by Django 5.2.8 on 2026-03-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_id_document_user_kyc_decision_user_kyc_report_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classification_confidence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='classification_evidence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='classification_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role_classification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
