# Generated by Django 4.2.7 on 2026-03-28 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_shopkeeperproduct_vendorproduct_and_more'),
        ('cart', '0004_alter_cartitem_product'),
        ('orders', '0006_alter_orderitem_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_products', to='products.category'),
        ),
        migrations.AddField(
            model_name='vendorproduct',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopkeeperproduct',
            name='shopkeeper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shopkeeperproduct',
            name='vendor_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeeper_listings', to='products.vendorproduct'),
        ),
        migrations.AlterUniqueTogether(
            name='shopkeeperproduct',
            unique_together={('shopkeeper', 'vendor_product')},
        ),
    ]
