# Generated by Django 4.2.7 on 2026-03-28 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_delete_product_vendorproduct_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeperproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_products/'),
        ),
        migrations.AddField(
            model_name='shopkeeperproduct',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shopkeeperproduct',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name='ProductUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shopkeeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_usages', to=settings.AUTH_USER_MODEL)),
                ('vendor_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='products.vendorproduct')),
            ],
            options={
                'unique_together': {('vendor_product', 'shopkeeper')},
            },
        ),
    ]
