# Generated by Django 5.2.8 on 2026-03-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_billing_partial_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeperproduct',
            name='bill_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopkeeperproduct',
            name='locked_cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
