# Generated by Django 5.2.8 on 2026-03-28 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_bill_generated_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopkeeperbilling',
            name='purchase_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='products.purchaserequest'),
        ),
    ]
