# Generated by Django 5.1.4 on 2026-09-11 14:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_method_order_razorpay_order_id_and_more'),
        ('products', '0012_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='unique_review_per_order',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='products_re_shopkee_fe91c2_idx',
            old_name='products_re_shopke_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='products_re_custome_b538a4_idx',
            old_name='products_re_custome_idx',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('customer', 'shopkeeper_product', 'order')},
        ),
    ]
