# Generated by Django 4.2.7 on 2026-09-11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [('products', '0013_remove_review_unique_review_per_order_and_more')]

    operations = [
        migrations.AddField(model_name='purchaserequest', name='assigned_delivery', field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_purchase_requests', to=settings.AUTH_USER_MODEL)),
        migrations.AddField(model_name='purchaserequest', name='delivery_address', field=models.TextField(blank=True)),
        migrations.AddField(model_name='purchaserequest', name='delivery_status', field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('PICKED_UP', 'Picked up'), ('OUT_FOR_DELIVERY', 'Out for delivery'), ('DELIVERED', 'Delivered')], default='ASSIGNED', max_length=25)),
        migrations.AddField(model_name='purchaserequest', name='description', field=models.TextField(blank=True)),
        migrations.AddField(model_name='purchaserequest', name='latitude', field=models.FloatField(blank=True, null=True)),
        migrations.AddField(model_name='purchaserequest', name='longitude', field=models.FloatField(blank=True, null=True)),
    ]
